Repository aws-cloudformation/aws-guard-rules-registry, pull requests merged in 2022-08, with the labels that each got.

#213 fix: publish 204
  .github/workflows/publish.yml
  docker/Dockerfile
  docs/Using-Guard-Rules-Registry.md
  mappings/build.py
  rules/aws/amazon_s3/s3_bucket_policy_grantee_check.guard
Labels: fix

#214 fix: env path
  docker/Dockerfile
  docs/Using-Guard-Rules-Registry.md
Labels: documentation, cicd, fix

#215 fix: publish 1.0.1
  docker/Dockerfile
  docs/Using-Guard-Rules-Registry.md
Labels: fix

#220 feat: Add small improvements to publish.yaml
  .github/workflows/publish.yml
Labels: cicd, refactor

#219 feat: Make docker image work with non-root users
  docker/Dockerfile
Labels: cicd, refactor
